services:
  app:
    image: fitboost:local
    container_name: fitboost_app
    restart: always
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fitboost-net
    expose:
      - "9000"
    volumes:
      - fitboost_storage:/var/www/html/storage
      - fitboost_cache:/var/www/html/bootstrap/cache
      - fitboost_static:/var/www/html/public

  nginx:
    image: nginx:1.27-alpine
    container_name: fitboost_nginx
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - fitboost_storage:/var/www/html/storage:ro
      - fitboost_static:/var/www/html/public
    networks:
      - fitboost-net

  db:
    image: mariadb:10.11
    container_name: fitboost_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fitboost-net

volumes:
  fitboost_storage:
  fitboost_cache:
  fitboost_static:
  db_data:

networks:
  fitboost-net:
    driver: bridge
